HELP.HTML <<- paste(
  'This Shiny app uses techniques described in the Coursera <a',
  'href="https://www.coursera.org/course/predmachlearn"><i>Practical',
  'Machine Learning</i></a> class.<br>',
  '<hr> <b>Concept</b>:&nbsp; Use interactive interface to select',
  'machine learning parameters for the <a',
  'href="http://caret.r-forge.r-project.org/">caret package</a> to',
  'solve a problem involving image segmentation.&nbsp; This interactive',
  'interface may provide insights on best machine learning approach for',
  'a given problem.&nbsp; Future:&nbsp; perhaps with small set of',
  'metadata, the approach could be used with a variety of problems and',
  'datasets.<br><br>',
  'To see data:  library(AppliedPredictiveModeling) and then',
  'data(segmentationOriginal).<br><br>',
  'Some variables with near-zero variance and/or high correlation to',
  'other variables have been removed.',
  '<hr> <b>Inputs</b>:&nbsp; At the left, select various preprocessing',
  'options and caret method.<br>',
  '<br>',
  '<b>Fit tab</b>:&nbsp; Output from caret train function applied to',
  'subset of original training data.<br>',
  '<br>',
  '<b>ConfusionMatrix tab</b>:&nbsp; Confusion matrix, sensitivity,',
  'specificity and related data from caret confusionMatrix function',
  'applied to an out-of-sample validation dataset. Use to compare',
  'models.&nbsp; [A final test set is reserved and is not used in the',
  'current implementation.]<br>',
  '<br>',
  '<b>DotPlot tab</b>:&nbsp; dotPlot using output from caret varImp',
  'function that gives importance rankings of variables included in the',
  'fit.<br>',
  '<hr> <b>Reference</b>:&nbsp; Andrew A Hill, Peter LaPan, Yizheng Li',
  'and Steve Haney.&nbsp; <a',
  'href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2080643/">Impact',
  'of image segmentation on high-content screening data quality for',
  'SK-BR-3 cells</a>, <i>BMC Bioinformatics</i>, Sept. 2007.')
html.note<-paste("Note:  Approximate processing times above are for a 2.4 GHz Intel i7-3630QM CPU.",
                 "All models work on a local server, but only lda and rpart work at shinyapps.io.")

